# Generated by Django 4.1.6 on 2023-02-14 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('link', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1024)),
                ('title_photo', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EventViewer.category')),
                ('user', models.ManyToManyField(related_name='attending', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
