# Generated by Django 4.1.6 on 2023-02-16 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EventViewer', '0006_alter_comment_options_remove_event_title_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
