# Generated by Django 4.1.6 on 2023-03-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventViewer', '0009_alter_event_options_alter_event_end_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_at']},
        ),
    ]
